[package]
name = "extern_crate"
version = "0.1.0"
authors = ["John Jacko <jljacko@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

passwords = {version = "3.1.3", features = ["crypto"]}